name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          scope: conventional-actions
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - run: npm ci
      - run: npm run all
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - uses: ./
        with:
          platforms: |
            linux/amd64
            linux/arm64
            darwin/amd64
            darwin/arm64
            windows/amd64
      - run: ls -lR .build

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  packages: read
