name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run all
      - uses: ./
        with:
          buildvcs: auto
          buildmode: default
          trimpath: true
          #package: ./cmd/*
          #platforms:
          #tags:
      - run: ls -lR .build
